# Generated by Django 5.2.3 on 2025-06-19 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backgroundimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=50)),
                ('route_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BusRoute',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='approved',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_tracking',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='vehicle_number',
        ),
        migrations.AddField(
            model_name='driver',
            name='bus',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.bus'),
            preserve_default=False,
        ),
    ]
