# Generated by Django 5.2.3 on 2025-06-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_active_backgroundimage_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stops', models.JSONField()),
            ],
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='user',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='is_tracking',
            new_name='approved',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='current_lat',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='current_lng',
            new_name='longitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='backgroundimage',
            name='image',
            field=models.ImageField(upload_to='background/'),
        ),
        migrations.DeleteModel(
            name='Bus',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
    ]
