# Generated by Django 5.2.3 on 2025-06-19 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_route_remove_passenger_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='longitude',
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
