# Generated by Django 5.2.3 on 2025-06-19 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_driver_latitude_remove_driver_longitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stops', models.TextField(help_text='Comma-separated stops (e.g., "Stop1,Stop2,Stop3")')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='BackgroundImage',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='driver',
            old_name='approved',
            new_name='verified',
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='busroute',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='core.driver'),
        ),
    ]
