# Generated by Django 5.2.4 on 2025-07-23 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_busroute_delete_backgroundimage_delete_route_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_plate', models.CharField(max_length=50)),
                ('total_seats', models.PositiveIntegerField(default=25)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='core.driver')),
            ],
        ),
        migrations.AddField(
            model_name='busroute',
            name='bus',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route', to='core.bus'),
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='core.bus')),
            ],
        ),
    ]
