# Generated by Django 5.2.4 on 2025-08-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_message_pickuprequest_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='current_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='current_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
